name: Pull Request
on:
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: 20.10.0

jobs:
  linting:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Continuous integration
        uses: ./.github/actions/setup

      - name: Lint Application
        run: npm run lint